// -----------------------------------------------------------------------------
// array_mult8.v -- 8x8 unsigned array multiplier (flat structural)
//
// Generated by samples/generate_array_mult.py
//
// Topology: classic Braun array multiplier.
//   - Partial products p[i][j] = a[i] & b[j]    (64 AND gates)
//   - Reduction tree:   56 full_adders in (N-1) x N grid
//   - Final result:     16 bits
//
// Exercises: critical path (carry chain), fanout (each a[i] drives 8 ANDs),
//            longest-path-on-DAG, regular-array structure detection.
//
// License: public-domain textbook design.
// -----------------------------------------------------------------------------

module full_adder (
    input  wire a,
    input  wire b,
    input  wire cin,
    output wire sum,
    output wire cout
);
    wire ab, acin, bcin;
    xor (sum,  a, b, cin);
    and (ab,   a, b);
    and (acin, a, cin);
    and (bcin, b, cin);
    or  (cout, ab, acin, bcin);
endmodule


module array_mult8 (
    input  wire [7:0] a,
    input  wire [7:0] b,
    output wire [15:0]  product
);

    // ------------------------------------------------------------
    // Partial products: p_i_j = a[i] & b[j]
    // ------------------------------------------------------------
    wire p_0_0;
    and (p_0_0, a[0], b[0]);
    wire p_0_1;
    and (p_0_1, a[0], b[1]);
    wire p_0_2;
    and (p_0_2, a[0], b[2]);
    wire p_0_3;
    and (p_0_3, a[0], b[3]);
    wire p_0_4;
    and (p_0_4, a[0], b[4]);
    wire p_0_5;
    and (p_0_5, a[0], b[5]);
    wire p_0_6;
    and (p_0_6, a[0], b[6]);
    wire p_0_7;
    and (p_0_7, a[0], b[7]);
    wire p_1_0;
    and (p_1_0, a[1], b[0]);
    wire p_1_1;
    and (p_1_1, a[1], b[1]);
    wire p_1_2;
    and (p_1_2, a[1], b[2]);
    wire p_1_3;
    and (p_1_3, a[1], b[3]);
    wire p_1_4;
    and (p_1_4, a[1], b[4]);
    wire p_1_5;
    and (p_1_5, a[1], b[5]);
    wire p_1_6;
    and (p_1_6, a[1], b[6]);
    wire p_1_7;
    and (p_1_7, a[1], b[7]);
    wire p_2_0;
    and (p_2_0, a[2], b[0]);
    wire p_2_1;
    and (p_2_1, a[2], b[1]);
    wire p_2_2;
    and (p_2_2, a[2], b[2]);
    wire p_2_3;
    and (p_2_3, a[2], b[3]);
    wire p_2_4;
    and (p_2_4, a[2], b[4]);
    wire p_2_5;
    and (p_2_5, a[2], b[5]);
    wire p_2_6;
    and (p_2_6, a[2], b[6]);
    wire p_2_7;
    and (p_2_7, a[2], b[7]);
    wire p_3_0;
    and (p_3_0, a[3], b[0]);
    wire p_3_1;
    and (p_3_1, a[3], b[1]);
    wire p_3_2;
    and (p_3_2, a[3], b[2]);
    wire p_3_3;
    and (p_3_3, a[3], b[3]);
    wire p_3_4;
    and (p_3_4, a[3], b[4]);
    wire p_3_5;
    and (p_3_5, a[3], b[5]);
    wire p_3_6;
    and (p_3_6, a[3], b[6]);
    wire p_3_7;
    and (p_3_7, a[3], b[7]);
    wire p_4_0;
    and (p_4_0, a[4], b[0]);
    wire p_4_1;
    and (p_4_1, a[4], b[1]);
    wire p_4_2;
    and (p_4_2, a[4], b[2]);
    wire p_4_3;
    and (p_4_3, a[4], b[3]);
    wire p_4_4;
    and (p_4_4, a[4], b[4]);
    wire p_4_5;
    and (p_4_5, a[4], b[5]);
    wire p_4_6;
    and (p_4_6, a[4], b[6]);
    wire p_4_7;
    and (p_4_7, a[4], b[7]);
    wire p_5_0;
    and (p_5_0, a[5], b[0]);
    wire p_5_1;
    and (p_5_1, a[5], b[1]);
    wire p_5_2;
    and (p_5_2, a[5], b[2]);
    wire p_5_3;
    and (p_5_3, a[5], b[3]);
    wire p_5_4;
    and (p_5_4, a[5], b[4]);
    wire p_5_5;
    and (p_5_5, a[5], b[5]);
    wire p_5_6;
    and (p_5_6, a[5], b[6]);
    wire p_5_7;
    and (p_5_7, a[5], b[7]);
    wire p_6_0;
    and (p_6_0, a[6], b[0]);
    wire p_6_1;
    and (p_6_1, a[6], b[1]);
    wire p_6_2;
    and (p_6_2, a[6], b[2]);
    wire p_6_3;
    and (p_6_3, a[6], b[3]);
    wire p_6_4;
    and (p_6_4, a[6], b[4]);
    wire p_6_5;
    and (p_6_5, a[6], b[5]);
    wire p_6_6;
    and (p_6_6, a[6], b[6]);
    wire p_6_7;
    and (p_6_7, a[6], b[7]);
    wire p_7_0;
    and (p_7_0, a[7], b[0]);
    wire p_7_1;
    and (p_7_1, a[7], b[1]);
    wire p_7_2;
    and (p_7_2, a[7], b[2]);
    wire p_7_3;
    and (p_7_3, a[7], b[3]);
    wire p_7_4;
    and (p_7_4, a[7], b[4]);
    wire p_7_5;
    and (p_7_5, a[7], b[5]);
    wire p_7_6;
    and (p_7_6, a[7], b[6]);
    wire p_7_7;
    and (p_7_7, a[7], b[7]);

    // ------------------------------------------------------------
    // Sum and carry wires for each row's full-adder array
    // ------------------------------------------------------------
    wire s_1_0, c_1_0;
    wire s_1_1, c_1_1;
    wire s_1_2, c_1_2;
    wire s_1_3, c_1_3;
    wire s_1_4, c_1_4;
    wire s_1_5, c_1_5;
    wire s_1_6, c_1_6;
    wire s_1_7, c_1_7;
    wire s_2_0, c_2_0;
    wire s_2_1, c_2_1;
    wire s_2_2, c_2_2;
    wire s_2_3, c_2_3;
    wire s_2_4, c_2_4;
    wire s_2_5, c_2_5;
    wire s_2_6, c_2_6;
    wire s_2_7, c_2_7;
    wire s_3_0, c_3_0;
    wire s_3_1, c_3_1;
    wire s_3_2, c_3_2;
    wire s_3_3, c_3_3;
    wire s_3_4, c_3_4;
    wire s_3_5, c_3_5;
    wire s_3_6, c_3_6;
    wire s_3_7, c_3_7;
    wire s_4_0, c_4_0;
    wire s_4_1, c_4_1;
    wire s_4_2, c_4_2;
    wire s_4_3, c_4_3;
    wire s_4_4, c_4_4;
    wire s_4_5, c_4_5;
    wire s_4_6, c_4_6;
    wire s_4_7, c_4_7;
    wire s_5_0, c_5_0;
    wire s_5_1, c_5_1;
    wire s_5_2, c_5_2;
    wire s_5_3, c_5_3;
    wire s_5_4, c_5_4;
    wire s_5_5, c_5_5;
    wire s_5_6, c_5_6;
    wire s_5_7, c_5_7;
    wire s_6_0, c_6_0;
    wire s_6_1, c_6_1;
    wire s_6_2, c_6_2;
    wire s_6_3, c_6_3;
    wire s_6_4, c_6_4;
    wire s_6_5, c_6_5;
    wire s_6_6, c_6_6;
    wire s_6_7, c_6_7;
    wire s_7_0, c_7_0;
    wire s_7_1, c_7_1;
    wire s_7_2, c_7_2;
    wire s_7_3, c_7_3;
    wire s_7_4, c_7_4;
    wire s_7_5, c_7_5;
    wire s_7_6, c_7_6;
    wire s_7_7, c_7_7;

    // ------------------------------------------------------------
    // Row 0: product[0] = p_0_0
    // ------------------------------------------------------------
    assign product[0] = p_0_0;

    // ------------------------------------------------------------
    // Row 1: add partial products p_1_*
    // ------------------------------------------------------------
    full_adder fa_1_0 (.a(p_0_1), .b(p_1_0), .cin(1'b0), .sum(s_1_0), .cout(c_1_0));
    full_adder fa_1_1 (.a(p_0_2), .b(p_1_1), .cin(c_1_0), .sum(s_1_1), .cout(c_1_1));
    full_adder fa_1_2 (.a(p_0_3), .b(p_1_2), .cin(c_1_1), .sum(s_1_2), .cout(c_1_2));
    full_adder fa_1_3 (.a(p_0_4), .b(p_1_3), .cin(c_1_2), .sum(s_1_3), .cout(c_1_3));
    full_adder fa_1_4 (.a(p_0_5), .b(p_1_4), .cin(c_1_3), .sum(s_1_4), .cout(c_1_4));
    full_adder fa_1_5 (.a(p_0_6), .b(p_1_5), .cin(c_1_4), .sum(s_1_5), .cout(c_1_5));
    full_adder fa_1_6 (.a(p_0_7), .b(p_1_6), .cin(c_1_5), .sum(s_1_6), .cout(c_1_6));
    full_adder fa_1_7 (.a(1'b0), .b(p_1_7), .cin(c_1_6), .sum(s_1_7), .cout(c_1_7));
    assign product[1] = s_1_0;

    // ------------------------------------------------------------
    // Row 2: add partial products p_2_*
    // ------------------------------------------------------------
    full_adder fa_2_0 (.a(s_1_1), .b(p_2_0), .cin(1'b0), .sum(s_2_0), .cout(c_2_0));
    full_adder fa_2_1 (.a(s_1_2), .b(p_2_1), .cin(c_2_0), .sum(s_2_1), .cout(c_2_1));
    full_adder fa_2_2 (.a(s_1_3), .b(p_2_2), .cin(c_2_1), .sum(s_2_2), .cout(c_2_2));
    full_adder fa_2_3 (.a(s_1_4), .b(p_2_3), .cin(c_2_2), .sum(s_2_3), .cout(c_2_3));
    full_adder fa_2_4 (.a(s_1_5), .b(p_2_4), .cin(c_2_3), .sum(s_2_4), .cout(c_2_4));
    full_adder fa_2_5 (.a(s_1_6), .b(p_2_5), .cin(c_2_4), .sum(s_2_5), .cout(c_2_5));
    full_adder fa_2_6 (.a(s_1_7), .b(p_2_6), .cin(c_2_5), .sum(s_2_6), .cout(c_2_6));
    full_adder fa_2_7 (.a(c_1_7), .b(p_2_7), .cin(c_2_6), .sum(s_2_7), .cout(c_2_7));
    assign product[2] = s_2_0;

    // ------------------------------------------------------------
    // Row 3: add partial products p_3_*
    // ------------------------------------------------------------
    full_adder fa_3_0 (.a(s_2_1), .b(p_3_0), .cin(1'b0), .sum(s_3_0), .cout(c_3_0));
    full_adder fa_3_1 (.a(s_2_2), .b(p_3_1), .cin(c_3_0), .sum(s_3_1), .cout(c_3_1));
    full_adder fa_3_2 (.a(s_2_3), .b(p_3_2), .cin(c_3_1), .sum(s_3_2), .cout(c_3_2));
    full_adder fa_3_3 (.a(s_2_4), .b(p_3_3), .cin(c_3_2), .sum(s_3_3), .cout(c_3_3));
    full_adder fa_3_4 (.a(s_2_5), .b(p_3_4), .cin(c_3_3), .sum(s_3_4), .cout(c_3_4));
    full_adder fa_3_5 (.a(s_2_6), .b(p_3_5), .cin(c_3_4), .sum(s_3_5), .cout(c_3_5));
    full_adder fa_3_6 (.a(s_2_7), .b(p_3_6), .cin(c_3_5), .sum(s_3_6), .cout(c_3_6));
    full_adder fa_3_7 (.a(c_2_7), .b(p_3_7), .cin(c_3_6), .sum(s_3_7), .cout(c_3_7));
    assign product[3] = s_3_0;

    // ------------------------------------------------------------
    // Row 4: add partial products p_4_*
    // ------------------------------------------------------------
    full_adder fa_4_0 (.a(s_3_1), .b(p_4_0), .cin(1'b0), .sum(s_4_0), .cout(c_4_0));
    full_adder fa_4_1 (.a(s_3_2), .b(p_4_1), .cin(c_4_0), .sum(s_4_1), .cout(c_4_1));
    full_adder fa_4_2 (.a(s_3_3), .b(p_4_2), .cin(c_4_1), .sum(s_4_2), .cout(c_4_2));
    full_adder fa_4_3 (.a(s_3_4), .b(p_4_3), .cin(c_4_2), .sum(s_4_3), .cout(c_4_3));
    full_adder fa_4_4 (.a(s_3_5), .b(p_4_4), .cin(c_4_3), .sum(s_4_4), .cout(c_4_4));
    full_adder fa_4_5 (.a(s_3_6), .b(p_4_5), .cin(c_4_4), .sum(s_4_5), .cout(c_4_5));
    full_adder fa_4_6 (.a(s_3_7), .b(p_4_6), .cin(c_4_5), .sum(s_4_6), .cout(c_4_6));
    full_adder fa_4_7 (.a(c_3_7), .b(p_4_7), .cin(c_4_6), .sum(s_4_7), .cout(c_4_7));
    assign product[4] = s_4_0;

    // ------------------------------------------------------------
    // Row 5: add partial products p_5_*
    // ------------------------------------------------------------
    full_adder fa_5_0 (.a(s_4_1), .b(p_5_0), .cin(1'b0), .sum(s_5_0), .cout(c_5_0));
    full_adder fa_5_1 (.a(s_4_2), .b(p_5_1), .cin(c_5_0), .sum(s_5_1), .cout(c_5_1));
    full_adder fa_5_2 (.a(s_4_3), .b(p_5_2), .cin(c_5_1), .sum(s_5_2), .cout(c_5_2));
    full_adder fa_5_3 (.a(s_4_4), .b(p_5_3), .cin(c_5_2), .sum(s_5_3), .cout(c_5_3));
    full_adder fa_5_4 (.a(s_4_5), .b(p_5_4), .cin(c_5_3), .sum(s_5_4), .cout(c_5_4));
    full_adder fa_5_5 (.a(s_4_6), .b(p_5_5), .cin(c_5_4), .sum(s_5_5), .cout(c_5_5));
    full_adder fa_5_6 (.a(s_4_7), .b(p_5_6), .cin(c_5_5), .sum(s_5_6), .cout(c_5_6));
    full_adder fa_5_7 (.a(c_4_7), .b(p_5_7), .cin(c_5_6), .sum(s_5_7), .cout(c_5_7));
    assign product[5] = s_5_0;

    // ------------------------------------------------------------
    // Row 6: add partial products p_6_*
    // ------------------------------------------------------------
    full_adder fa_6_0 (.a(s_5_1), .b(p_6_0), .cin(1'b0), .sum(s_6_0), .cout(c_6_0));
    full_adder fa_6_1 (.a(s_5_2), .b(p_6_1), .cin(c_6_0), .sum(s_6_1), .cout(c_6_1));
    full_adder fa_6_2 (.a(s_5_3), .b(p_6_2), .cin(c_6_1), .sum(s_6_2), .cout(c_6_2));
    full_adder fa_6_3 (.a(s_5_4), .b(p_6_3), .cin(c_6_2), .sum(s_6_3), .cout(c_6_3));
    full_adder fa_6_4 (.a(s_5_5), .b(p_6_4), .cin(c_6_3), .sum(s_6_4), .cout(c_6_4));
    full_adder fa_6_5 (.a(s_5_6), .b(p_6_5), .cin(c_6_4), .sum(s_6_5), .cout(c_6_5));
    full_adder fa_6_6 (.a(s_5_7), .b(p_6_6), .cin(c_6_5), .sum(s_6_6), .cout(c_6_6));
    full_adder fa_6_7 (.a(c_5_7), .b(p_6_7), .cin(c_6_6), .sum(s_6_7), .cout(c_6_7));
    assign product[6] = s_6_0;

    // ------------------------------------------------------------
    // Row 7: add partial products p_7_*
    // ------------------------------------------------------------
    full_adder fa_7_0 (.a(s_6_1), .b(p_7_0), .cin(1'b0), .sum(s_7_0), .cout(c_7_0));
    full_adder fa_7_1 (.a(s_6_2), .b(p_7_1), .cin(c_7_0), .sum(s_7_1), .cout(c_7_1));
    full_adder fa_7_2 (.a(s_6_3), .b(p_7_2), .cin(c_7_1), .sum(s_7_2), .cout(c_7_2));
    full_adder fa_7_3 (.a(s_6_4), .b(p_7_3), .cin(c_7_2), .sum(s_7_3), .cout(c_7_3));
    full_adder fa_7_4 (.a(s_6_5), .b(p_7_4), .cin(c_7_3), .sum(s_7_4), .cout(c_7_4));
    full_adder fa_7_5 (.a(s_6_6), .b(p_7_5), .cin(c_7_4), .sum(s_7_5), .cout(c_7_5));
    full_adder fa_7_6 (.a(s_6_7), .b(p_7_6), .cin(c_7_5), .sum(s_7_6), .cout(c_7_6));
    full_adder fa_7_7 (.a(c_6_7), .b(p_7_7), .cin(c_7_6), .sum(s_7_7), .cout(c_7_7));
    assign product[7] = s_7_0;

    // ------------------------------------------------------------
    // Upper half: from last reduction row
    // ------------------------------------------------------------
    assign product[8] = s_7_1;
    assign product[9] = s_7_2;
    assign product[10] = s_7_3;
    assign product[11] = s_7_4;
    assign product[12] = s_7_5;
    assign product[13] = s_7_6;
    assign product[14] = s_7_7;
    assign product[15] = c_7_7;
endmodule
