"""
generate_array_mult.py
======================
Generate a parameterized N x N unsigned array multiplier as flat structural
Verilog (primitive AND gates + full_adder instances).

This is the classic textbook array-multiplier topology used in every digital
design course. We generate it programmatically so the resulting netlist is:
  - 100% original (no third-party IP)
  - Parameterizable in width (default 8x8 -> ~64 full adders + 64 ANDs)
  - Visually striking (2D regular grid of FAs)

Run from repo root:

    python samples/generate_array_mult.py            # default 8x8 -> array_mult8.v
    python samples/generate_array_mult.py 16         # 16x16    -> array_mult16.v
"""
from __future__ import annotations

import sys
from pathlib import Path


HEADER = """// -----------------------------------------------------------------------------
// array_mult{N}.v -- {N}x{N} unsigned array multiplier (flat structural)
//
// Generated by samples/generate_array_mult.py
//
// Topology: classic Braun array multiplier.
//   - Partial products p[i][j] = a[i] & b[j]    ({sq_pp} AND gates)
//   - Reduction tree:   {n_fa} full_adders in (N-1) x N grid
//   - Final result:     {twoN} bits
//
// Exercises: critical path (carry chain), fanout (each a[i] drives {N} ANDs),
//            longest-path-on-DAG, regular-array structure detection.
//
// License: public-domain textbook design.
// -----------------------------------------------------------------------------

module full_adder (
    input  wire a,
    input  wire b,
    input  wire cin,
    output wire sum,
    output wire cout
);
    wire ab, acin, bcin;
    xor (sum,  a, b, cin);
    and (ab,   a, b);
    and (acin, a, cin);
    and (bcin, b, cin);
    or  (cout, ab, acin, bcin);
endmodule


module array_mult{N} (
    input  wire [{Nm1}:0] a,
    input  wire [{Nm1}:0] b,
    output wire [{P}:0]  product
);
"""


def emit(N: int) -> str:
    P = 2 * N - 1
    Nm1 = N - 1
    n_fa = (N - 1) * N
    sq_pp = N * N

    out = [HEADER.format(N=N, Nm1=Nm1, P=P, sq_pp=sq_pp, n_fa=n_fa, twoN=2 * N)]

    # Partial products: p[i][j] = a[i] & b[j]
    out.append("    // ------------------------------------------------------------")
    out.append("    // Partial products: p_i_j = a[i] & b[j]")
    out.append("    // ------------------------------------------------------------")
    for i in range(N):
        for j in range(N):
            out.append(f"    wire p_{i}_{j};")
            out.append(f"    and (p_{i}_{j}, a[{i}], b[{j}]);")

    # Sum / carry intermediate wires
    out.append("")
    out.append("    // ------------------------------------------------------------")
    out.append("    // Sum and carry wires for each row's full-adder array")
    out.append("    // ------------------------------------------------------------")
    for row in range(1, N):
        for col in range(N):
            out.append(f"    wire s_{row}_{col}, c_{row}_{col};")

    # Row 0: product[0] is just p_0_0
    out.append("")
    out.append("    // ------------------------------------------------------------")
    out.append("    // Row 0: product[0] = p_0_0")
    out.append("    // ------------------------------------------------------------")
    out.append("    assign product[0] = p_0_0;")

    # Reduction rows: row r adds p_r_j to (previous row's sum / partial product)
    for row in range(1, N):
        out.append("")
        out.append(f"    // ------------------------------------------------------------")
        out.append(f"    // Row {row}: add partial products p_{row}_*")
        out.append(f"    // ------------------------------------------------------------")
        for col in range(N):
            # 'a' input: previous row sum (or partial product if row==1)
            if row == 1:
                a_in = f"p_0_{col + 1}" if col + 1 < N else "1'b0"
            else:
                a_in = f"s_{row - 1}_{col + 1}" if col + 1 < N else f"c_{row - 1}_{N - 1}"
            # 'b' input: this row's partial product
            b_in = f"p_{row}_{col}"
            # carry-in: this row's previous-column carry, or 0 for col 0
            cin = "1'b0" if col == 0 else f"c_{row}_{col - 1}"
            out.append(
                f"    full_adder fa_{row}_{col} ("
                f".a({a_in}), .b({b_in}), .cin({cin}), "
                f".sum(s_{row}_{col}), .cout(c_{row}_{col}));"
            )
        # The col=0 sum of this row is product[row]
        out.append(f"    assign product[{row}] = s_{row}_0;")

    # Top half of product from last row's sums and final carry
    out.append("")
    out.append("    // ------------------------------------------------------------")
    out.append("    // Upper half: from last reduction row")
    out.append("    // ------------------------------------------------------------")
    for col in range(1, N):
        out.append(f"    assign product[{N - 1 + col}] = s_{N - 1}_{col};")
    out.append(f"    assign product[{P}] = c_{N - 1}_{N - 1};")

    out.append("endmodule")
    out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    N = int(argv[1]) if len(argv) > 1 else 8
    if N < 2 or N > 32:
        print(f"N must be in [2, 32]; got {N}", file=sys.stderr)
        return 2
    out_path = Path(__file__).resolve().parent / f"array_mult{N}.v"
    out_path.write_text(emit(N), encoding="utf-8")
    print(f"Wrote {out_path}")
    print(f"  Width:        {N} x {N}")
    print(f"  Partial-prod: {N * N} AND gates")
    print(f"  Full adders:  {(N - 1) * N}")
    print(f"  Total prims:  ~{N * N + (N - 1) * N * 5} primitive gates "
          f"(each FA expands to 5 primitives)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))


def main_cli() -> int:
    """Zero-arg wrapper used by the `synthesis-generate-mult` console script."""
    return main(sys.argv)
